### ISSUE TITLE
App twitching as UXCam records the session

### ISSUE THREAD

**Issue by repi10** [uxcam/cordova-uxcam#13] opened 2019-06-30 20:27 UTC
Hi, after implementation of cordova-uxcam v3.0.2 there is noticeable "twitch" of app elements as the session is being recorded.

It hapens as soon as Acodec exeutes (
I/ACodec: [OMX.qcom.video.encoder.avc] Now Idle->Executing
[OMX.qcom.video.encoder.avc] Now Executing)

**Comment by susanuxcam** [comment] 2019-12-30 09:11
Hey @repi10! I'm sorry for such a delayed reply! Could you test the most recent SDK version and let us know if the issue persists? Thanks!

**Comment by S-AT** [comment] 2020-03-30 23:25
The same problem here:
While recording, CSS animations are choppy, touch events fire with sporadic delays or get missed at all.

**Comment by susanuxcam** [comment] 2020-03-31 09:31
hey @S-AT can you tell me which SDK version you're using?

**Comment by S-AT** [comment] 2020-03-31 23:44
> hey @S-AT can you tell me which SDK version you're using?

I see the problem since 2018, when I started using your service. 
And I always use the most recent version.

**Comment by susanuxcam** [comment] 2020-04-14 10:13
Hey again, does your app perform video encoding?

**Comment by S-AT** [comment] 2020-04-15 22:27
> Hey again, does your app perform video encoding?

No

**Comment by susanuxcam** [comment] 2020-04-16 09:09
Thanks, we'll try to replicate the issue and we'll keep you posted.

**Comment by Klapik** [comment] 2022-09-20 18:20
The problem is still noticeable with the latest sdk.
We are forced to give up using the library.

**Comment by davvyy00** [comment] 2022-09-22 11:12
The scroll events has become really sluggish after we started using uxcam, is anyone listening? Or should we just cancel our subscription. "cordova-uxcam": "^3.5.1"

**Comment by gabmadera** [comment] 2022-09-22 11:37
Hello @Klapik , @davvyy00 is this happening for Android or iOS or both? 

For Android, would you be able to try passing the configuration option `enableImprovedScreenCapture` as **`true`** and check if this helps?

For iOS, would you please try passing the configuration option `enableAdvancedGestureRecognition` as **`false`** and give it a try? 

[Here's](https://developer.uxcam.com/docs/cordova) the updated documentation for Cordova.

**Comment by davvyy00** [comment] 2022-09-22 11:42
@gabmadera it's happening for both Android and IOS, I will try this and update when, I get my next version into production

**Comment by gabmadera** [comment] 2022-09-22 11:44
@davvyy00  thank you, pelase do let me knwo if this helps.

**Comment by davvyy00** [comment] 2022-09-22 11:47
@gabmadera I can't find enableImprovedScreenCapture and enableAdvancedGestureRecognition is the documentation

**Comment by gabmadera** [comment] 2022-09-22 11:55
@davvyy00 apologies, the team will update this doc asap. An example of usage for this config options is: 

```
UXCam.optIntoSchematicRecordings() //To enable session video recording on iOS 
const configuration = { 
userAppKey: 'YOUR API KEY',
enableImprovedScreenCapture: true,
enableAdvancedGestureRecognition: false
 } 
UXCam.startWithConfiguration(configuration);
```

**Comment by pf-mahmoud** [comment] 2023-05-21 17:55
We still face the glitch and slowness in the both android and iOS apps.
We are using the most recent SDK version.

**Comment by DFDIEGOH** [comment] 2023-06-26 14:04
Hey @pf-mahmoud Apologies for the delay - Can you share which UXcam SDK you are currently using? As well as how you are initializing the SDK in your application?

**Comment by vikas-parsa-cbh** [comment] 2023-06-26 14:08
Hey @DFDIEGOH, We are also facing the same issue. Here is [loom](https://www.loom.com/share/1c9dcd7a48344a3fa0489893751776d3) explaining the same. We are using `3.6.0`

**Comment by DFDIEGOH** [comment] 2023-06-26 15:06
Hey @vikas-parsa-cbh Would it be possible to test and try on old devices (< iPhone 13 pro) and see if you are able to replicate this on your end?

**Comment by vikas-parsa-cbh** [comment] 2023-06-26 17:13
@DFDIEGOH I am able to reproduce this on iPhone 12 too. https://www.loom.com/share/7b018d256b0d421eb40a78acf454f217

**Comment by S-AT** [comment] 2023-06-26 17:26
@vikas-parsa-cbh , this problem is 4 years old. This is not a **bug**, this is how it works **by design**.

They will ask you questions, then they will disappear with no response.
Don't waste your time and money. Uninstall.

**Comment by DFDIEGOH** [comment] 2023-06-26 19:23
Thank you for sharing this @vikas-parsa-cbh - We will be investigating this with the team, as soon as I get more updates I will let you know. Appreciate your patience in this regard. 

We appreciate the feedback and at the same time I want to apologize for the experience you had in the past with UXCam @S-AT We have improved our bug fixing/release process in which also improves the experience our customers have with UXCam. We will be targeting this with the highest priority on our end and keep you posted as soon as we get any updates in this regard.

**Comment by DFDIEGOH** [comment] 2023-07-06 16:16
Hi everyone! Great news - The team has released a new version of the Cordova SDK that contains the fix of this issue. This is version 3.6.1 of our Cordova Package. 

Really looking forward on getting your feedback in this regard!

**Closed as completed** 2023-07-12 06:46 UTC
